const contactLength = () =>
  JSON.parse(localStorage.getItem("contactLength"))?.[0]?.code;

export const regx = {
  onlyNumber: /^\d*(\.)?(\d{0,2})?$/,
  twoDigitValue: /^\d{2}$/,
  id: /^.{1,20}$/,
  mobileNumber: new RegExp(`^\\d{${contactLength()}}$`),
  // email: /[a-z0-9]+@[a-z0-9]+\.[a-z0-9]{2,3}/,
  email: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
  commaSeperatedEmail:
    /^([a-zA-Z0-9.]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,3})(,[a-zA-Z0-9.]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,3})*$/,
  //amount: new RegExp(`^\\d{1,3}(,?\\d{3})*(\\.\\d{0,${DECIMAL_DEGIT}})?$`), // will create this /^\d{0,50}(\.\d{0,6})?$/
  contact: new RegExp(`^\\d{${contactLength()}}$`),
  commaSeperatedContact: new RegExp(
    `^\\d{${contactLength()}}(,\\d{${contactLength()}})*$`,
  ),
  amountLabel:
    /Amount|balance|Price|Charge(?!Id|Name|Code|Type|dUsage)|budgetLimit|userTransactionLimit|Rate(?!Time)|Denomination(?!Name)/i,
  cardNumber: /^\d{1,16}$/,
  commaSeperatedNumber: /^\d+(,\d+)*$/,
  // generate regex for positive number with deciaml and number can be enter in string also like "123.45"
  onlyPositiveNumber: /^\d*(\.\d+)?$/,
  integerNumber: /^[1-9]\d*$/,
};

export const approvalRoleConfig = {
  4: "adjustment_user_role",
  23: "adjustment_user_role",
  32: "adjustment_user_role",
  25: "transfer_user_role",
  28: "transfer_user_role",
  1: "cancellation_user_role",
  3: "refund_user_role",
  12: "disputes_user_role",
  13: "credit_cancellation_user_role",
  20: "billable_debit_cancellation_user_role",
  22: "ura_credit_debit_cancellation_user_role",
  2: "cancellation_user_role",
};

export const serviceReq = {
  makePayment: {
    name: "Make Payment",
    icon: "makePaymentIcon",
    code: "makePayment",
    permission: {
      profile: "view360.fe.makepayment.profile.create",
      account: "view360.fe.makepayment.account.create",
      service: "view360.fe.makepayment.service.create",
    },
    featureId: "6",
  },
  creditDebitAdjustment: {
    name: "Credit/Debit Adjustment",
    permission: {
      profile: "view360.fe.adjustments.profile.create",
      account: "view360.fe.adjustments.account.create",
      service: "view360.fe.adjustments.service.create",
    },
    icon: "creditDebitAdjustmentIcon",
    code: "creditDebitAdjustment",
    featureId: "4",
  },
  balanceTransfer: {
    name: "Balance Transfer",
    icon: "balanceTransferIcon",
    code: "balanceTransfer",
    featureId: "28",
    permission: {
      profile: "view360.fe.balancetransfer.profile.create",
      account: "view360.fe.balancetransfer.account.create",
      service: "view360.fe.balancetransfer.service.create",
    },
  },
  cancelPayment: {
    name: "Cancel Payment",
    icon: "cancelPaymentIcon",
    permission: {
      profile: "view360.fe.cancelpayment.profile.create",
      account: "view360.fe.cancelpayment.account.create",
      service: "view360.fe.cancelpayment.service.create",
    },
    code: "cancelPayment",
    featureId: "1",
  },
  refundOfCredit: {
    name: "Refund of Credit",
    icon: "refundOfCreditIcon",
    code: "refundOfCredit",
    featureId: "3",
    permission: {
      profile: "view360.fe.refund.profile.create",
      account: "view360.fe.refund.account.create",
      service: "view360.fe.refund.service.create",
    },
  },
  raiseDisputes: {
    name: "Raise Disputes",
    icon: "raiseDisputesIcon",
    code: "raiseDisputes",
    featureId: "12",
    permission: {
      profile: "view360.fe.disputes.profile.create",
      account: "view360.fe.disputes.account.create",
      service: "view360.fe.disputes.service.create",
    },
  },
  cancelDebitAdjustment: {
    name: "Cancel Credit Adjustment",
    icon: "cancelDebitAdjustmentIcon",
    code: "cancelDebitAdjustment",
    featureId: "13",
    permission: {
      profile: "view360.fe.canceladjustment.profile.create",
      account: "view360.fe.canceladjustment.account.create",
      service: "view360.fe.canceladjustment.service.create",
    },
  },
  unclaimedBalance: {
    name: "Accounts with Unclaimed Balance",
    icon: "balanceTransferIcon",
    code: "unclaimedBalance",
    featureId: "26",
    permission: {
      profile: "view360.fe.unclaimedbalance.profile.create",
      account: "view360.fe.unclaimedbalance.account.create",
      service: "view360.fe.unclaimedbalance.service.create",
    },
  },
  billableDebitCancellation: {
    name: "Billable Debit Cancellation",
    icon: "billableDebitCancellationIcon",
    code: "billableDebitCancellation",
    featureId: "20",
    permission: {
      profile: "view360.fe.billabledebitcancellation.profile.create",
      account: "view360.fe.billabledebitcancellation.account.create",
      service: "view360.fe.billabledebitcancellation.service.create",
    },
  },
  balanceTransferCancellation: {
    name: "Balance Transfer Cancellation",
    icon: "makePaymentIcon",
    code: "balanceTransferCancellation",
    featureId: "25",
    permission: {
      profile: "view360.fe.balancetransfercancellation.profile.create",
      account: "view360.fe.balancetransfercancellation.account.create",
      service: "view360.fe.balancetransfercancellation.service.create",
    },
  },
  URAcreditDebitAdjustment: {
    name: "URA Credit/Debit Adjustment",
    permission: {
      profile: "view360.fe.uraadjustments.profile.create",
      account: "view360.fe.uraadjustments.account.create",
      service: "view360.fe.uraadjustments.service.create",
    },
    icon: "creditDebitAdjustmentIcon",
    code: "URAcreditDebitAdjustment",
    featureId: "4",
  },
  URACreditDebitCancellation: {
    name: "URA Adjustment Cancellation",
    permission: {
      profile: "view360.fe.uraadjustmentsCancellation.profile.create",
      account: "view360.fe.uraadjustmentsCancellation.account.create",
      service: "view360.fe.uraadjustmentsCancellation.service.create",
    },
    icon: "creditDebitAdjustmentIcon",
    code: "URACreditDebitCancellation",
    featureId: "22",
  },
  URAInvoiceReversal: {
    name: "URA Invoice Reversal",
    icon: "cancelPaymentIcon",
    permission: {
      profile: "view360.fe.urainvoicereversal.profile.create",
      account: "view360.fe.urainvoicereversal.account.create",
      service: "view360.fe.urainvoicereversal.service.create",
    },
    code: "URAInvoiceReversal",
    reasonKeyCode: "4",
    featureId: "2",
  },
};
export const AdjustmentTypeMapping = {
  C: 4,
  D: 23,
  B: 32,
};
export const receiptDownloadConfigIds = {
  makePayment: "receiptName",
  creditAdjustment: "adjustmentReportName",
  debitAdjustment: "adjustmentDebitReportName",
};

export const DATABASE_COL_NAM_MAPPING = {
  outstandingAmount: "opendbamount",
  overdueAmount: "overduedbamt",
};

export const commonSortableTableColumn = [
  "accountNumber",
  "accountId",
  "group",
  "overdueAmount",
  "outstandingAmount",
  "debtAge",
];

export const STATUS_MAPPING = {
  1: "Waiting for Approval",
  2: "Active",
  3: "Skipped",
  4: "Delayed",
  5: "Added",
  6: "Rejected",
  7: "Uploaded",
  8: "Completed",
  10: "Waiting for customer Confirmation",
  11: "Waiting for Supervisor Approval",
  12: "Waiting for Director Approval",
  13: "Awaiting CFO Email Approval",
  9: "Promise to Pay Breached",
  15: "Void",
};

export const statusTagStyleMapping = {
  "5-1": "vividViolet",
  "5-2": "forestGreen",
  "5-3": "twilightBlue",
  "7-4": "roseGlow",
  "7-5": "mintyFresh",
  "7-6": "roseGlow",
  "5-": "vanillaCustard",
  "7-": "forestGreen",
  Completed: "roseGlow",
  "In-progress": "vanillaCustard",
  Pending: "vanillaCustard2",
  Cleared: "roseGlow",
  "Completed-Customer Already Paied": "roseGlow",
  "In-Progress-0": "vanillaCustard",
  "In-Progress": "vanillaCustard",
  "In-Progress-Call Later": "vividViolet",
  "Completed-0": "roseGlow",
  "Pending-0": "vanillaCustard2",
  "In-Progress-No Answer": "forestGreen",
  "In-Progress-Not Reachable": "twilightBlue",
  "Completed-Promise To Pay (PTP)": "roseGlow",
  "Completed-Refuse To Pay (RTP)": "mintyFresh",
  "In-Progress Call Later": "vividViolet",
  "In-Progress PTP Rejected": "roseGlow",
};

export const ACCOUNT_DETAILS_STATUS_CODE = {
  legal: 1,
  sod: 2,
  writeOff: 3,
  prelegal: 4,
  ptpBreach: 5,
  terminate: 6,
  temporaryOutOfService: 7,
  barOutgoingService: 8,
  inDunning: 9,
};

export const ACCOUNT_STATUS_COLOR_MAPPING = {
  [ACCOUNT_DETAILS_STATUS_CODE.legal]: "vanillaCustard",
  [ACCOUNT_DETAILS_STATUS_CODE.prelegal]: "vanillaCustard",
  [ACCOUNT_DETAILS_STATUS_CODE.sod]: "error",
  [ACCOUNT_DETAILS_STATUS_CODE.writeOff]: "roseGlow",
  [ACCOUNT_DETAILS_STATUS_CODE.ptp]: "twilightBlue",
  [ACCOUNT_DETAILS_STATUS_CODE.ptpBreach]: "twilightBlue",
  [ACCOUNT_DETAILS_STATUS_CODE.terminate]: "error",
  [ACCOUNT_DETAILS_STATUS_CODE.temporaryOutOfService]: "error",
  [ACCOUNT_DETAILS_STATUS_CODE.barOutgoingService]: "twilightBlue",
  [ACCOUNT_DETAILS_STATUS_CODE.inDunning]: "vanillaCustard",
};

export const HISTORY_STATUS_MAPPING = {
  0: "Pending",
  1: "Success",
};

export const ACCOUNT_DETAILS_STATUS_LABEL_MAPPING = {
  [ACCOUNT_DETAILS_STATUS_CODE.legal]: "Legal",
  [ACCOUNT_DETAILS_STATUS_CODE.prelegal]: "Pre-Legal",
  [ACCOUNT_DETAILS_STATUS_CODE.sod]: "SOD",
  [ACCOUNT_DETAILS_STATUS_CODE.writeOff]: "Write-Off",
  [ACCOUNT_DETAILS_STATUS_CODE.ptp]: "PTP",
  [ACCOUNT_DETAILS_STATUS_CODE.ptpBreach]: "PTP-Breach",
  [ACCOUNT_DETAILS_STATUS_CODE.terminate]: "Terminate",
  [ACCOUNT_DETAILS_STATUS_CODE.temporaryOutOfService]:
    "Temporary Out of Service",
  [ACCOUNT_DETAILS_STATUS_CODE.barOutgoingService]: "Bar Outgoing Service",
  [ACCOUNT_DETAILS_STATUS_CODE.inDunning]: "In-Dunning",
};

export const NOTES_AND_REMINDERS_STATUS_LABEL_MAPPING = {
  low: "low",
  Medium: "medium",
  High: "high",
  Critical: "critical",
};

export const DUNNING_ACTION_STATUS_MAPPING = {
  0: "Unpaid",
  1: "Paid",
};
export const PAUSE_DUNNING_REASON = {
  1: "Exclude From Dunning",
  2: "Customer Paid Bills",
};

export const actionTypeMapping = {
  M: "Manual",
  A: "Auto",
};

export const FOLLOW_UP_TYPE = {
  R: "Regular",
  L: "Legal",
  M: "Manual Bar - Unbar",
  S: "Sibilling",
};

export const LEGAL_CASE_BUTTON_MAPPING = {
  1: "File Legal Case",
  2: "Hearing",
  3: "Judgement",
  4: "Appeal",
  5: "Enforcement",
  6: "Close",
  7: "Legal Reject",
};

export const BULK_STATUS_MAPPING = {
  0: "In Queue",
  1: "Processed",
  2: "Rejected",
  3: "Waiting For Approval",
  4: "Ready To Process",
  5: "Processed",
  6: "Failed",
  7: "Cancelled",
};

export const HISTORY_PTP_MAPPING = {
  2: "Active",
  8: "Completed",
  9: "Breached",
  6: "Rejected",
};
// for Legal-process
export const LEGAL_PROCESS_STATUS = {
  0: "Pre-legal",
  1: "Legal",
  2: "Not Eligible",
};
export const HISTORY_PTP_TYPE_MAPPING = {
  POPINSTALLMENT: "Installment",
  POPDATE: "PTP Future Date",
};
export const HISTORY_IRREGULAR_MAPPING = {
  1: "Regular Payer",
  0: "Irregular Payer",
};
export const HISTORY_IRREGULAR_ACTION_TYPE = {
  M: "Manual",
  A: "Auto",
};

export const FOLLOW_UP_STATUS_MAPPING = {
  "5-1": "In-Progress-Call Later",
  "5-2": "In-Progress-No Answer",
  "5-3": "In-Progress-Not Reachable",
  "7-4": "Completed-PTP",
  "7-5": "Completed-RTP",
  "7-6": "Completed-Customer Already Paied",
  "5-": "In-Progress-",
  "7-": "Completed-",
  5: "In Progress",
  7: "Completed/Closed",
  1: "Pending",
  "In-progress": "In-progress",
  Completed: "Completed",
  Pending: "Pending",
  Cleared: "Cleared",
  "Completed-Customer Already Paied": "Completed-Customer Already Paied",
  "In-Progress-Call Later": "In-Progress-Call Later",
  "In-Progress-No Answer": "In-Progress-No Answer",
  "In-Progress-Not Reachable": "In-Progress-Not Reachable",
  "Completed-PTP": "Completed-PTP",
  "Completed-RTP": "Completed-RTP",
  "In-Progress-": "In-Progress-",
  "Completed-": "Completed-",
};

export const FOLLOW_UP_STATUS_TAGSTYLE_MAPPING = {
  "5-1": "vividViolet",
  "5-2": "forestGreen",
  "5-3": "twilightBlue",
  "7-4": "roseGlow",
  "7-5": "mintyFresh",
  "7-6": "roseGlow",
  "5-": "vanillaCustard",
  "7-": "forestGreen",
  5: "vanillaCustard",
  7: "forestGreen",
  1: "vanillaCustard",
  2: "forestGreen",
};
export const EXCLUSION_STATUS = {
  "%": "All",
  2: "Active",
  6: "Rejected",
  15: "Void",
};

export const MANUAL_FOLLOW_UP_STATUS = {
  1: "Pending",
  2: "Approved",
  5: "In Progress",
  7: "Completed",
  4: "Skipped",
  3: "Delayed",
  10: "Waiting for customer Confirmation",
  11: "Waiting for Supervisor Approval",
  12: "Waiting for Director Approval",
  13: "Awaiting CFO Email Approval",
  9: "Promise to Pay Breached",
  14: "Waiting For Approval",
};
export const Action_For_Bulk_operation = {
  32: "3",
  113: "17",
  114: "18",
  110: "19",
  104: "20",
  105: "21",
  45: "22",
  103: "23",
  102: "24",
  44: "25",
  43: "26",
  42: "27",
  36: "28",
  34: "29",
  33: "30",
  31: "31",
  30: "32",
  16: "33",
  28: "34",
  14: "35",
  13: "36",
};
export const STATUS_MAPPING_2 = {
  ...STATUS_MAPPING,
  2: "Completed",
};

export const globalConfigFeature =
  "allowedDecimalSeparator,allowedFieldSeparator,disablePtintForDebitNote,iscollectiondunning,budgetApprovalRequired,uploadDocSize,downloadRecordsLimit,adjustmentTaxDetails,isSelfApproval,printReceipt,paymentPromptValidation,URAapplicable,BulkReceipt,bulkPaymentReportName,amountToWords,zrauncode,taxamountdescription,manualpaymentposting,displayOpenDebitTaxDetails,validatepaymentReference";

export const metaDataCategory =
  "disputestatus,uploadedfilesummarystatus,bulkUploadReason,alertType,autodebitdetailsstatus,feature,entitylevels,approvalType,transactionsautoadjustflag,creditadjustrules,paymentcriteria,transactionsfinpostingstatus,paymodes,creditdebit,transactionkey,transactionsstatus,transactionBasedOn,creditadjustrulesforcrdbnotes,adjustmenttypes,debittype,adjustmentsearch,operationTypes,subscriberStatus,depositsearch,autoDebitsearch,viewAutoDebitsearch,isApplicable,chequebounceaction,chequesstatus,chequesearchtypes,chequeactions,languages,fincategories,articlecategory,approvals,approverstatus,transactionkey,uploadecategory,todosdashboardfeatures,dunningActionType,dunningActionTime,paymentdetailsstatusdescription,paymentreferencesearchbasedon,uraadjustmenttypes,impactonrevenue,isDeemed,historyFilterForURA,historyFilter,autoadjustflag,yesorno,articleStatus,paymentdetailsstatusdescription,hasHeader,transactionLimitType,cancelledHistoryStatus";

export const ACTION_TYPE_MAPPING = {
  actionType: {
    1: "Dunning Approval",
    2: "Pop Approval",
    3: "Recovery Date Approval",
    4: "Manual Follow",
    5: "Cheque",
    6: "Installments",
  },
};
export const APPROVAL_STATUS_MAPPING = {
  0: "Waiting for Approval",
  1: "Approved",
  2: "Rejected",
};
export const NOTIFICATIONS_STATUS_MAPPING = {
  0: "Pending",
  1: "Sent",
  2: "Failed",
  deliveryNotPosted: "Failed",
  deliveryPosted: "Success",
};

export const DELIVERY_MAPPING = {
  0: "deliveryNotPosted",
  1: "deliveryPosted",
};

export const LEGEL_PROCESS_STATUS = {
  1: "Pre-legal",
  2: "Not Eligible",
};
// 0 - profile 1 - account 2 - service
export const customerSearchEndPoints = {
  1: "subscribers/profile/CompositeProfile/V1",
  2: "subscribers/billing-account/CompositeBillingAccount/V1",
  3: "subscribers/service-account/CompositeServiceAccount/V1",
  // 3: 'subscribers/service-account/ServiceAccountByServiceID'
};
export const activeEntityLevalName = {
  1: "profile",
  2: "account",
  3: "service",
};

export const customPaginationLimit = {
  1: 10,
  2: 25,
  3: 50,
  4: 100,
};

export const customTextTooltips = (text, charCount) => {
  if (text.length > charCount) {
    return `${text.slice(0, charCount)}...`;
  }
  return text;
};

export const permissionConfigOthers = {
  ["blacklist"]: {
    label: "Blacklist",
    name: "blacklist",
    view: "debt.fe.blacklistgrid.view",
    download: "debt.fe.blacklistgrid.download",
  },
  ["history"]: {
    label: "Followup History",
    name: "history",
    view: "debt.fe.followuphistory.view",
    download: "debt.fe.followuphistory.download",
  },

  ["disputeList"]: {
    label: "Dispute List",
    name: "disputeList",
    view: "debt.fe.disputegrid.view",
    download: "debt.fe.disputegrid.download",
  },
  ["performance"]: {
    label: "Performance",
    name: "performance",
    view: "debt.fe.performance.view",
    download: "debt.fe.performance.download",
  },
  ["debtSoldHistory"]: {
    label: "Debt Sold History",
    name: "debtSoldHistory",
    view: "debt.fe.soldaccountgrid.view",
    download: "debt.fe.soldaccountgrid.download",
  },
  ["assignmentHistory"]: {
    label: "Assignment History",
    name: "assignmentHistory",
    view: "debt.fe.assignmenthistorygrid.view",
    download: "debt.fe.assignmenthistorygrid.download",
  },
};

export const permissionConfig = {
  ["Templates"]: {
    create: "debt.fe.templates.create",
    view: "debt.fe.templates.view",
  },
  ["User Leave Details"]: {
    create: "debt.fe.userleave.create",
    view: "debt.fe.userleave.view",
  },
  ["User Role Map"]: {
    create: "debt.fe.userrole.create",
    view: "debt.fe.userrole.view",
  },
  ["Dunning Holidays"]: {
    create: "debt.fe.dunningholidays.create",
    view: "debt.fe.dunningholidays.view",
  },
  ["Sale Of Debt Agencies"]: {
    create: "debt.fe.purchaseagency.create",
    view: "debt.fe.purchaseagency.view",
  },
  ["Collection Agency"]: {
    create: "debt.fe.externalagency.create",
    view: "debt.fe.externalagency.view",
  },
  ["Debt Age Group"]: {
    create: "debt.fe.DebtAgeGroup.create",
    view: "debt.fe.DebtAgeGroup.view",
  },
  ["Dunning Schedules"]: {
    create: "debt.fe.DunningSchedules.create",
    view: "debt.fe.DunningSchedules.view",
  },
  ["Bad Debt Provisioning"]: {
    create: "debt.fe.BadDebtProvisioning.create",
    view: "debt.fe.BadDebtProvisioning.view",
  },
};

export const STATUS_BACKGROUND_MAPPING = {
  1: "warning",
  2: "success",
  3: "warning",
  4: "warning",
  5: "warning",
  6: "error",
  7: "success",
  8: "success",
};

export const SCREEN_NAME = {
  LANDING_PAGE: "landingPage",
};

export const tableEditableColumnType = {
  instalmentDueDate: "date",
};

const constants = {
  LOCAL_STORAGE_LANG_KEY: "lang",
  flag: {
    MASKING_FLAG: "maskingFlag",
  },
  oAuth: {
    ACCESS_TOKEN: "access_token",
    ID_TOKEN: "ID_TOKEN",
    EXPIRES_AT: "expires_in",
    REFRESH_TOKEN: "refresh_token",
  },
  date: {
    DATE_FORMAT: "YYYY-MM-DD",
    DATE_FORMAT1: "DD/MMMM/YYYY",
    DATE_FORMAT2: "DD MMMM YYYY",
    DATE_FORMAT3: "DD-MM-YYYY",
    DATE_FORMAT4: "DD MMM YYYY",
    DATE_MONTH: "DD MMMM",
    DATE_TIME_FORMAT: "YYYY-MM-DD HH:mm:ss",
    DATE_TIME_FORMAT1: "D MMM YYYY h:mm A",
    DATE_TIME_FORMAT2: "YYYY-MM-DD h:mm:ss A",
    DATE_TIME_FORMAT3: "DD-MM-YYYY h:mm A",
    DATE_TIME_FORMAT4: "YYYY-DD-MM HH:mm:ss A",
    DATE_TIME_FORMAT5: "YYYY-MM-DD h:mm A",
    DATE_TIME_FORMAT6: "DD-MM-YYYY HH:mm:ss A",
    DATE_TIME_FORMAT7: "YYYY-MM-DD HH:mm:ss.SSS",
    TIME_FORMAT: "HH:mm",
    TIME_FORMAT2: "hh:mm",
    TIME_FORMAT3: "h:mm A",
    DATE_TIME_FORMAT_FULL: "DD MMM YYYY HH:mm",
    DATE_TIME_FORMAT_FULL1: "DD MMMM YYYY h:mm A",
    "360user": {
      DATE_FORMAT: "YYYY-MM-DD",
      DATE_FORMAT1: "DD/MM/YYYY",
      DATE_TIME_FORMAT: "DD/MM/YYYY HH:mm:ss",
      DATE_TIME_FORMAT1: "D MMM YYYY h:mm A",
      DATE_TIME_FORMAT2: "DD/MM/YYYY HH:MM A",
      DATE_TIME_FORMAT_AM_PM: "DD/MM/YYYY HH:MM A",
      DATE_TIME_SEC_AM_PM_FORMAT: "DD/MM/YYYY HH:mm:ss A",
    },
    dateLabel: [
      "holdingDate",
      "createdDate",
      "accesseDate",
      "endDate",
      "startDate",
      "date",
      "holiday",
      "accessedDate",
      "installmentDate",
      "actionDate",
      "futureDate",
      "caseDate",
      "acknowledgedDate",
      "followUpDate",
      "statusChangeDate",
      "startDate",
      "endDate",
      "transDate",
      "transactionDate",
      "fromDate",
      "billstartdate",
      "billenddate",
      "cardExpiryDate",
      "invoiceDate",
      "invoiceDueDate",
      "chequeDate",
      "excludeStartDate",
      "excludeEndDate",
      "validityStartDate",
      "validityEndDate",
      "adjustedDate",
      "expiryDate",
      "scheduleDate",
      "unbarTillDate",
      "validityFrom",
      "validityTo",
      "toDate",
      "createdOn",
      "issueDate",
      "releaseDate",
      "date &Time",
      "manualExclusionCreateDate",
      "depositionDate",
      "createdAt",
      "billingRunStartTime",
      "START_TIME",
      "completeAt",
      "scheduleTime",
      "initiatedDateAndTime",
      "approvedDateAndTime",
      "modifiedOn",
      "modifiedDate",
      "blacklistedDate",
      "fileDateTime",
      "processingTime",
      "cdrTime",
      "processedDate",
      "approvedDate",
      "raisedOn",
      "TIME",
      "dueDate",
      "uploadedDateTime",
      "processedDateTime",
      "billPeriodTo",
      "billPeriodFrom",
      "transactiondate",
      "legalFeeDate",
      "ptpEndDate",
      "CREATED_ON",
      "eventTime",
      "chargeStartDate",
      "chargeEndDate",
      "eventDateTime",
      "requestedDate",
      "irregularPayerDate",
      "irregularPayerEndDate",
      "removeIrregularPayerDate",
      //'soldDate',
      "invoiceDate",
      "lastPaymentDate",
      "caseDateTime",
      "UPLOADED_ON",
      "PROCESSED_DATE_TIME",
      "MODIFIED_ON",
      "legalCaseDate",
      "REMOVAL_DATE",
      "CREATED_AT",
      "initiatedDateTime",
      "approvedDateTime",
      "resumeDate",
      "lastUpdatedOn",
      "activationDate",
      "START_DATE",
      "requestRaisedDate",
      "startDateTime",
      "endDateTime",
      "closedDate",
      "created_date",
      "modifiedAt",
      "TIME",
      "blacklistDate",
      "instalmentDueDate",
      "Un Blacklist End Date",
      "ptpFutureDate",
      "write-OffDate",
      "qualifyDate",
      "writeoffDate",
      "lastUpdateOn",
      "accountTerminationDate",
      "accountActivationDate",
      "ptpEndate",
      "disputeRequestCreatedDate",
      "approved/rejectedDate",
      "quaifyDate",
      "initiatedDate",
      "asOnDate",
      "cancelledDate",
    ],
    dateLabelWithTime: [
      "statusChangeDate",
      "createdDate",
      "actionDate",
      "followUpDate",
      "accessedDate",
      // 'startDate',
      // 'endDate',
      "modifiedDate",
      "modifiedOn",
      "unBlacklistedDate",
      "statusChangedDate",
      "transactionDate",
      "processedDateTime",
      "adjustedDate",
      "date &Time",
      "depositionDate",
      "createdAt",
      "createdOn",
      "billingRunStartTime",
      "START_TIME",
      "completeAt",
      "scheduleTime",
      "initiatedDateAndTime",
      "approvedDateAndTime",
      "uploadedDateTime",
      "transactiondate",
      "UPLOADED_ON",
      "PROCESSED_DATE_TIME",
      "MODIFIED_ON",
      "caseDateTime",
      "legalCaseDate",
      "CREATED_AT",
      "initiatedDateTime",
      "approvedDateTime",
      "lastUpdatedOn",
      "accesseDate",
      "requestRaisedDate",
      "startDateTime",
      "endDateTime",
      "modifiedAt",
      "TIME",
      "fileDateTime",
      "processedDate",
      "lastUpdateOn",
      "ptpEndate",
      "createdDateTime",
      "approved/rejectedDate",
      "requestedDate",
      "initiatedDate",
      "asOnDate",
    ],
    dateLabelWithTime2: ["processingTime", "cdrTime"],
    dateLabelWithTime3: ["TIME"],
  },
  label: {
    accountId: "Account Number",
    customerID: "Customer Id",
    ageOfDebt: "Debt Age",
    openInvoice: "Open Invoices",
    idcsLoginName: "Supervisor",
    amountToBeRecovered: "Debt Pending Recovered",
    amountRecovered: "Debt Amount Recovered",
    idcaLoginName: "Agent",
    RequestType: "Request Type",
    templateId: "Template Id",
    networkActionType: "Network Type",
    mediaType: "Media Type",
    templateDescription: "Template Description",
    AcNumber: "Account Number",
    loginName: "Login Name",
    startDate: "Start Date",
    endDate: "End Date",
    reason: "Reason",
    createdBy: "Created By",
    createdDate: "Created Date",
    description: "Description",
    roleDescription: "Role",
    type: "Type",
    id: "ID",
    accessedBy: "Accessed By",
    accessedDate: "Accessed Date",
    holiday: "Holiday",
    status: "Status",
    assignedTask: "Assigned A/C",
    riskCategory: "Credit Color",
    customerName: "Customer Name",
    segment: "Segment",
    nationality: "Nationality",
    contactNumber: "Contact No",
    alternateContact: "Alternate Contact",
    alternateEmail: "Alternate Email",
    alternateContactNo: "Alternate Contact Number",
    totalRecords: "Total Records",
    recordsProcessed: "Records Processes",
    recordsFailed: "Records Failed",
    actionFor: "Category",
    RN: "RN",
    approved: "Approved",
    skipped: "Skipped",
    delayed: "Delayed",
    addAccounts: "Add Accounts",
    fileName: "File Name",
    statusDescription: "Status Description",
    actionDescription: "Message",
    identificationNumber: "ID No",
    templateid: "Dunning Action",
    uploadDateTime: "Upload Date and Time",
    actionType: "Action Type",
    followUpDate: "Follow Up Date",
    followUpType: "Follow Up Type",
    insNo: "Sr No",
    installmentAmount: "Installment Amount",
    installmentDate: "Due Date",
    chequeNumber: "Cheque No",
    totalInvoice: "Total Invoices",
    recoveryDays: "Recovery Days",
    transactionNumber: "Transaction Number",
    comments: "Comment",
    comment: "Comments",
    blacklistID: "Blacklist ID",
    blacklistedDate: "date",
    blacklistedBy: "Created By",
    invoiceNumber: "Invoice Number",
    invoiceAmount: "Invoice Amount",
    invoicePendingAmount: "Invoice Pending Amt.",
    invoiceDate: "Invoice Date",
    invoiceDueDate: "Invoice Due Date",
    featureDate: "Feature Date",
    installmentType: "Installment Type",
    installmentBasedOn: "Installment Based On",
    disputeType: "Dispute Type",
    amount: "Amount",
    serialNumber: "Serial No",
    accountIds: "Accounts",
    salePrice: "Sale Price",
    agencyId: "Agency Id",
    dateAndTime: "Date and Time",
    soldBy: "Sold by",
    agencyName: "Agency Name",
    address: "Address",
    contactEmail: "Contact Email",
    contactPerson: "Contact Person",
    edcsLoginName: "External Supervisor",
    edcaLoginName: "External Agent",
    openInvoiceAmount: "Open Invoice Amount",
    legalCaseStatus: "Legal Case Status",
    caseDate: "Case Date",
    acknowledgedBy: "Acknowledged By",
    caseId: "Case Id",
    acknowledgedDate: "Acknowledged Date",
    acknowledgementComments: "Acknowledgement Comments",
    profileType: "Customer Type",
    paymentDate: "Payment Date",
    paymentAmount: "Payment Amount",
    paymentMethod: "Payment Method",
    bankName: "Bank Name",
    chequeNo: "Cheque Number",
    trackingId: "Tracking ID",
    dateTime: "Date and Time",
    sendLinkVia: "Send link via",
    edcsSupervisor: "EDCS Supervisor",
    domainName: "Domain Name",
    statusChangeDate: "Status Change Date",
    futureDate: "Future Date",
    debtAmount: "Debt Amount",
    debtAge: "Debt Age",
    invoiceStatus: "Status",
    agentName: "Agent Name",
    performanceStatus: "Performance Status",
    customerType: "Customer Type",
    osAmount: "Promised Amount",
    installmentStatus: "Installment Status",
    dunningSchedule: "Dunning Schedule",
    totalInvoiceAmount: "Total Invoice Amount",
    overDueAmount: "Over Due Amount",
    recoveredAmount: "Recovered Amount",
    paymentDesc: "Payment Description",
    transAmount: "Transaction Amount",
    transDate: "Transaction Date",
    transNumber: "Transaction Number",
    userCode: "User Code",
    idNumber: "Id Number",
    unBlacklistedDate: "UnBlacklisted Date",
    unBalcklistedReson: "UnBalcklisted Reson",
    unBlacklistedBy: "UnBlacklisted By",
    profileId: "Profile Id",
    blacklistedReason: "Reason",
    statusChangedBy: "Status Changed By",
    statusChangedDate: "Status Changed Date",
    undisputeComments: "Undispute Comments",
    AGENCY_ID: " Agency ID",
    ACCOUNT_ID: "Account id",
    SALE_PRICE: "Sale Price",
    OUTSTANDING_AMT: "Outstanding Amount",
    TRANSACTION_NUM: "Transaction Number",
    SALE_DONE_BY: "Sale Done By",
    SALE_DATE: "Sale Date",
    userName: "User Name",
    categoryDescription: "Category Description",
    categoryCode: "Category Code",
    subCategoryDescription: "Sub Category Description",
    vipCode: "Vip Code",
    transactionKey: "Transaction Key",
    debitCredit: "Debit/Credit",
    transactionDate: "Transaction Date",
    clearedAmount: "Cleared Amount",
    entityCode: "Customer Id",
    entityName: "Customer Name",
    autoAdjustFlag: "Auto Adjust Flag",
    isCleared: "Is Transaction Cleared",
    taxAmount: "Tax Amount",
    channel: "Channel",
    correlationID: "Correlation Id",
    transactionOwner: "Transaction Owner",
    excessAmount: "Excess Amount",
    userAdditionalInfo: "User Location",
    reasons: "Reasons",
    // remarks: 'Description',
    financialPostingStatus: "Financial Posting Status",
    financialPostingReference: "Financial Posting Reference",
    payableAmount: "Payable Amount",
    billenddate: "Bill End Date",
    billstartdate: "Bill Start Date",
    disputeOn: "Dispute/Raised Against",
    approvedAmount: "Approved/Reject Amount",
    accessedByUser: "Approved/Rejected by",
    status_message: "Status",
    chargeId: "Charge Id",
    chargeType: "Charge Type",
    value: "Charge Amount",
    AccountID: "Account Id",
    SubscriberCurrency: "Subscriber Currency",

    totalOsAmount: "Total OS Amount",
    collectedAmount: "Collected Amount",
    popSuccessPercentage: "Pop Success Percentage",
    assignmentId: "Assignment Id",
    assignedBy: "Assigned By",
    fromUser: "From User",
    toUser: "To User",
    assignedDate: "Assigned Date",
    createdName: "Created User Name",
    Assign_Count: "Assign Count",
    name: "Name",
    intiatedDateAndTime: "Initiated Date And Time",
    approvedDateAndTime: "Approved Date And Time",
    remarks: "Remarks",
    "ProfileID/AccountID": "Profile ID / Account ID",
  },
  regex: {
    agencyId: regx.id,
    installmentAmount: regx.amount,
    alternateContact: regx.mobileNumber,
    alternateEmail: regx.email,
    additionalContacts: regx.mobileNumber,
    additionalEmails: regx.email,
    amount: regx.amount,
    salePrice: regx.amount,
    legalFees: regx.amount,
    contactEmail: regx.email,
    email: regx.email,
    contact: regx.mobileNumber,
    contactNumber: regx.mobileNumber,
    osAmount: regx.amount,
    numberOfDays: regx.onlyNumber,
    payableAmount: regx.amount,
    amountToRefund: regx.amount,
    debitAdjustmentAmount: regx.amount,
    creditAdjustmentAmount: regx.amount,
    Assign_Count: regx.onlyNumber,
    debtAgeStartDays: regx.onlyNumber,
    debtAgeEndDays: regx.onlyNumber,
    // groupID: regx.onlyNumber,
    acceleration: regx.onlyNumber,
    percentage: regx.onlyNumber,
    "ENTERACCOUNTNUMBER(S)": regx.onlyNumber,
    FROMACCOUNTNUMBER: regx.onlyNumber,
    TOACCOUNTNUMBER: regx.onlyNumber,
    ACCOUNTNUMBER: regx.onlyNumber,
    chequeNumber: /^[a-zA-Z0-9]{1,20}$/,
    cardNumber: regx.cardNumber,
    recipientsSMS: regx.commaSeperatedContact,
    recipientsEmail: regx.commaSeperatedEmail,
    NOTIFICATION_SUCCESS_RECIPIENTS_SMS: regx.commaSeperatedNumber,
    NOTIFICATION_SUCCESS_RECIPIENTS_SMS_1: regx.commaSeperatedNumber,
    NOTIFICATION_SUCCESS_RECIPIENTS_EMAIL: regx.commaSeperatedEmail,
    NOTIFICATION_SUCCESS_RECIPIENTS_EMAIL_1: regx.commaSeperatedEmail,
    NOTIFICATION_FAILED_RECIPIENTS_SMS: regx.commaSeperatedNumber,
    NOTIFICATION_FAILED_RECIPIENTS_SMS_1: regx.commaSeperatedNumber,
    NOTIFICATION_FAILED_RECIPIENTS_EMAIL: regx.commaSeperatedEmail,
    NOTIFICATION_FAILED_RECIPIENTS_EMAIL_1: regx.commaSeperatedEmail,
    userTransactionLimit: regx.onlyPositiveNumber,
  },
  dynamicRegex: function (arg) {
    return {
      contact: new RegExp(`^\\d{${contactLength()}}$`),
      recipientsSMS: new RegExp(
        `^\\d{${contactLength()}}(,\\d{${contactLength()}})*$`,
      ),
      enterManually: new RegExp(`^\\d{${contactLength()}}$`),
      contactNumber: new RegExp(`^\\d{${contactLength()}}$`),
    };
  },
  multiLineTextFields: [
    "reason",
    "description",
    "response",
    "notes",
    "address",
    "Response Comment",
    "blacklistedReason",
    "irregularPayerReason",
    "Comment",
    "comments",
    "newValue",
    "oldValue",
    "responseMessage",
    "changedTo",
    "changedFrom",
    "fileName",
    "cdr",
    "actiondesc",
    "document",
    "actionType",
    "disputedTransactionNumber",
    "commentsData",
  ],
  jsonFields: ["changedTo", "changedFrom"],
};

export const INDIAN_STATES = [
  { label: "Andhra Pradesh", value: "Andhra Pradesh" },
  { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
  { label: "Assam", value: "Assam" },
  { label: "Bihar", value: "Bihar" },
  { label: "Chhattisgarh", value: "Chhattisgarh" },
  { label: "Goa", value: "Goa" },
  { label: "Gujarat", value: "Gujarat" },
  { label: "Haryana", value: "Haryana" },
  { label: "Himachal Pradesh", value: "Himachal Pradesh" },
  { label: "Jharkhand", value: "Jharkhand" },
  { label: "Karnataka", value: "Karnataka" },
  { label: "Kerala", value: "Kerala" },
  { label: "Madhya Pradesh", value: "Madhya Pradesh" },
  { label: "Maharashtra", value: "Maharashtra" },
  { label: "Manipur", value: "Manipur" },
  { label: "Meghalaya", value: "Meghalaya" },
  { label: "Mizoram", value: "Mizoram" },
  { label: "Nagaland", value: "Nagaland" },
  { label: "Odisha", value: "Odisha" },
  { label: "Punjab", value: "Punjab" },
  { label: "Rajasthan", value: "Rajasthan" },
  { label: "Sikkim", value: "Sikkim" },
  { label: "Tamil Nadu", value: "Tamil Nadu" },
  { label: "Telangana", value: "Telangana" },
  { label: "Tripura", value: "Tripura" },
  { label: "Uttar Pradesh", value: "Uttar Pradesh" },
  { label: "Uttarakhand", value: "Uttarakhand" },
  { label: "West Bengal", value: "West Bengal" },
];

export default constants;
